### ISSUE TITLE
Rename project name

### ISSUE THREAD

**Issue by fabiohbarbosa** [rafaeljesus/easy-schedule#47]
The project name is incorrect.

**Schedule** = Cronograma
**Scheduler** = Agendador

**Comment by rafaeljesus** [comment]
I don't think so,

Schedule also means 'Agenda'

The intention of the project name was to be in pt `Agende Fácil` and not `Agendador Fácil` or `Fácil Agendador`

Is it clear for you?

**Comment by fabiohbarbosa** [comment]
I agree. Tks!
